apiVersion: v1
kind: Service
metadata:
  name: redisserver
  labels:
    app: redisserver
    service: redisserver
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    service: redisserver
